CREATE DATABASE IF NOT EXISTS hop_chafe_accounting CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE hop_chafe_accounting;

CREATE TABLE IF NOT EXISTS daily_records (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  record_date DATE NOT NULL UNIQUE,
  front_cups INT UNSIGNED NOT NULL DEFAULT 0,
  lineman_cups INT UNSIGNED NOT NULL DEFAULT 0,
  grab_cups INT UNSIGNED NOT NULL DEFAULT 0,
  shopee_cups INT UNSIGNED NOT NULL DEFAULT 0,
  cash_revenue DECIMAL(12,2) NOT NULL DEFAULT 0,
  transfer_revenue DECIMAL(12,2) NOT NULL DEFAULT 0,
  other_front_revenue DECIMAL(12,2) NOT NULL DEFAULT 0,
  lineman_revenue DECIMAL(12,2) NOT NULL DEFAULT 0,
  grab_revenue DECIMAL(12,2) NOT NULL DEFAULT 0,
  shopee_revenue DECIMAL(12,2) NOT NULL DEFAULT 0,
  ice_expense DECIMAL(12,2) NOT NULL DEFAULT 0,
  wage_expense DECIMAL(12,2) NOT NULL DEFAULT 0,
  cup_expense DECIMAL(12,2) NOT NULL DEFAULT 0,
  other_expense DECIMAL(12,2) NOT NULL DEFAULT 0,
  extra_expense_items LONGTEXT NULL,
  note VARCHAR(500) NOT NULL DEFAULT '',
  source VARCHAR(30) NOT NULL DEFAULT 'web',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_daily_date (record_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_items (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL UNIQUE,
  used_qty DECIMAL(12,2) NULL,
  remaining_qty DECIMAL(12,2) NULL,
  unit VARCHAR(100) NOT NULL DEFAULT '',
  sort_order INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cash_closings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  business_date DATE NOT NULL,
  expected_cash DECIMAL(12,2) NOT NULL DEFAULT 0,
  counted_cash DECIMAL(12,2) NOT NULL DEFAULT 0,
  variance DECIMAL(12,2) NOT NULL DEFAULT 0,
  closed_by VARCHAR(150) NOT NULL DEFAULT '',
  denominations JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_closing_date (business_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  first_name VARCHAR(150) NOT NULL,
  last_name VARCHAR(150) NOT NULL,
  failed_attempts INT UNSIGNED NOT NULL DEFAULT 0,
  locked_until DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO users (username, password_hash, first_name, last_name)
SELECT 'admin', '$2y$10$aHj3HOUVVia5HHY88zcr0OQot1DiTuOpuR5OWdvAljbdTbDEsjnye', 'Kittipong', 'Phudindong'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'admin');
